config/routes.rb
Photoman::Application.routes.draw do

  devise_for :users

  match 'show/:image_url' => 'images#show', :constraints => { :image_url => /.*/}
  match ':prefix' => 'home#index', :constraints => {:prefix => /.*/}

  root :to => 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :images

  def to_s
    title
  end

end

app/models/image.rb
class Image
#  belongs_to :album
#  image_accessor :imagefile
#  attr_accessor :url
  attr_accessor :imagefile
#  validates :album,     :presence => true
#  validates :imagefile, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

def show
  @album = Album.find(params[:id])
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

end

app/controllers/home_controller.rb
require 'find'

class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show

  end
  def new
    @image ||= Image.new
    @albums = Album.all
  end
  def create
    @image = Image.new(params[:image])
    if @image.save
      redirect_to album_path(@image.album)
    else
      new
      render :new
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper

def thumb_url( i, dimensions='60x60#' )
  i.imagefile.thumb(dimensions).url
#  Dragonfly[:images].remote_url_for(i.imagefile.uid)
end

def s3connection( key=ENV['S3_KEY'], secret=ENV['S3_SECRET'] )
  RightAws::S3.new( key, secret )
end

def s3bucket( bucket = ENV['S3_BUCKET'] )
  s3connection.bucket(bucket)
end

def dir_subdirs( options = {} )
  options = { :storage_mode=>'S3' }.merge(options)
  if options[:storage_mode] == 'S3'
    prefix = options[:prefix]
    prefix = prefix.to_s + "/" unless prefix.to_s == ""
    s3bucket.common_prefixes(prefix)
  end
end

def dir_contents( options = {} )
  options = { :storage_mode=>'S3' }.merge(options)
  if options[:storage_mode] == 'S3'
    prefix = options[:prefix]
    a = s3bucket.contents(prefix)
    a.shift
    a
  end
end

def dir_images( options = {} )

  images ||=   []
  dir_contents(options).each{  |f|
    if  ( i = Image.new ) &&
        ( i.imagefile = Dragonfly[:images].fetch(f) ) &&
        ( f.include?('.JPG') || f.include?('.jpg')  )
        images  <<  i

#  require 'RMagick'
#        i.imagefile.file do |f|
#          img = Magick::Image.read(f)[0]
#          exif = img.get_exif_by_entry.reduce(Hash.new) {|hash, entry| hash[entry[0]] = entry[1]; hash }
#          xmp               = XMP.parse(exif)
#          #          iptc = {}
#          #          img.each_iptc_dataset do |dataset, datafield|
#          #            iptc[dataset] = datafield
#          #          end
#          #          meta = { :exif => exif, :iptc => iptc }
#          logger.info ">>>>>--------------"
#          logger.info xmp
#          logger.info "<<<<<--------------"
#        end


    end
  }
  images
end

def dir_videos( options = {} )

  images ||=   []
  dir_contents(options).each{  |f|
    if  ( i = Image.new ) &&
        ( i.imagefile = Dragonfly[:images].fetch(f) ) &&
        ( f.include?('.m4v') || f.include?('.MOV') || f.include?('.mov') || f.include?('.avi') || f.include?('.AVI')  )
        images  <<  i
    end
  }
  images
end

#def s3_files
#  Dragonfly[:images].datastore.storage.directories.get(ENV['S3_BUCKET']).files
#end
#def images(options = {} )
#    options = { :storage_mode=>'S3' }.merge(options)

#    if options[:storage_mode] == 'S3'
##      connection  =   Fog::Storage.new({ :provider => 'AWS', :aws_access_key_id => ENV['S3_KEY'], :aws_secret_access_key => ENV['S3_SECRET'] })
#      images    ||=   []
#      dirs      ||= []
##      dirs      ||=   []
##      s3_files.each{  |f|
##        if ( i = Image.new ) &&
##           ( i.imagefile = Dragonfly[:images].fetch(f.key) ) &&
##           ( f.key.include?('.JPG') || f.key.include?('.jpg')  ) &&
##           ( options[:year].blank? ? true : f.key =~ /^#{options[:year]}\//  )
##           images  <<  i
##        else
##          dirs << i
##        end
##      }
#    elsif storage_mode == 'system'
#      @years = Dir['albums/*/'].map{|s| File.basename(s) }
#      year = params[:year].presence || @years.last
#      image_paths = Dir["albums/#{year}/**/*.JPG"] + Dir["albums/#{year}/**/*.jpg"]
#      images = []
#      image_paths.each{ |path|
#        url               = File.new(path).path.split('/').insert(1, thumb_size).join('/')
#        meta              = {}
#        e                 = EXIFR::JPEG.new(path)
#        xmp               = XMP.parse(e)
#        meta[:model]      = e.model
#        meta[:date_time]  = e.date_time
#        meta[:width]      = e.width
#        meta[:height]     = e.height
#        meta[:tags]       = xmp.dc.subject rescue []
#        meta[:rating]     = xmp.xmp.send('Rating').to_i rescue nil
#        year              = path.split('/')[1]
#        album             = path.split('/')[2]
#        images << {:year => year, :album => album, :path => path, :url => url, :meta => meta}
#      }
#      @images_by_albums = {}
#      @images_by_tags = {}

#      images.each{ |i|
#        @images_by_albums[ i[:album] ]  ||= []
#        @images_by_albums[ i[:album] ]  <<  i

#        i[:meta][:tags].each{ |t|
#          @images_by_tags[ t ]  ||= []
#          @images_by_tags[ t ]  <<  i
#        }

#      }
#      images
#    end
#  end


end

app/views/albums/_album.html.erb
<h1><%= album.title %></h1>
<%= render album.images %>

app/views/albums/show.html.erb
<%= render @album %>

app/views/application/_menu.html.erb
<%
  display_modes ||=   ['albums', 'tags']
%>

<p>
  Years:
  <% dir_subdirs.each do |d|  %>
    <% d.sub!('/','') %>
    <%= link_to d, :controller => :home, :action => :index, :prefix => d  %>
  <% end %>
</p>
<p>
  Display:
  <% display_modes.each do |g| %>
    <%= link_to g, :grouping => g %>
  <% end %>
</p>

<hr />

app/views/home/index.html.erb
<h1>Home</h1>

app/views/images/_image.html.erb
<%= image_tag image.imagefile.url %>

app/views/images/new.html.erb
<%= simple_form_for @image, :url => images_path do |f| %>

  <%= f.input :name %>
  <%= f.input :imagefile, :as => :file %>
  <%= f.input :album_id, :collection => @albums %>


  <%= f.button :submit %>

<% end %>

app/views/images/show.html.erb
<img src="<%= '/' + params[:image_url] %>" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photoman</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless notice.blank? %>
  <p class="notice"><%= notice %></p>
<% end %>
<% unless alert.blank? %>
  <p class="alert"><%= alert %></p>
<% end %>

<%= yield %>

<% if current_user %>
  <%= render :partial => 'menu' %>

  <h2><%= params[:year] %></h2>


  <% if false && images = images(:year=>params[:year]).presence %>
    <div class='images'>
      <ul>
        <% images.each do |i| %>
          <li><%= link_to( image_tag(thumb_url(i)), thumb_url(i,'500x500') )  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2><%= params[:prefix] %></h2>

  <% if s = dir_subdirs(:prefix => params[:prefix]).presence %>
    <h3>Subdirs</h3>
    <ul>
      <% s.each do |d| %>
        <li><%= link_to d, '/'+d %></li>
      <% end %>
    </ul>
  <% end %>

  <% if videos = dir_videos(:prefix => params[:prefix].to_s+"/").presence %>

	  <script type="text/javascript" src="/javascripts/jwplayer/jwplayer.js"></script>

    <h3>Videos</h3>
      <div id="jwplayer">JW Player goes here</div>

	      <script type="text/javascript">
          jwplayer("jwplayer").setup({
              flashplayer: "/javascripts/jwplayer/player.swf",
              playlist: [
                <% videos.each do |i| %>
                  <% remote_url = Dragonfly[:images].remote_url_for(i.imagefile.uid) %>
                  <% filename   = remote_url.split('/').last %>
                  { file: "<%= i.imagefile.url + '/' + filename %>", title: "<%= filename %>" },
                <% end %>
              ],
              "playlist.position": "right",
              "playlist.size": 260,
              width: 320+260,
              height: 240
          });
	      </script>

  <% end %>

  <% if images = dir_images(:prefix => params[:prefix].to_s+"/").presence %>
    <h3>Dir images</h3>
    <ul class='images'>
      <% images.each do |i| %>
        <% remote_url = Dragonfly[:images].remote_url_for(i.imagefile.uid) %>
        <% filename   = remote_url.split('/').last %>
        <li title="<%= filename %>"><%= link_to( image_tag(thumb_url(i)), '/show' + thumb_url(i,'500x500'))  %></li>
      <% end %>
    </ul>
  <% end %>


  <% if contents = dir_contents(:prefix => params[:prefix].to_s+"/").presence %>
    <h3>Dir contents</h3>
    <ul>
      <% contents.each do |f| %>
            <li><%= link_to f, Dragonfly[:images].remote_url_for(f)  %></li>
      <% end %>
    </ul>
  <% end %>

<% end %>

</body>
</html>